{
  config,
  pkgs,
  systemSettings,
  userSettings,
  ...
}:

{
  # Modules
  imports = [
    ./hardware-configuration.nix # Generated by the NixOS installer
    ./System/Hardware/Hardware-settings.nix # Personal hardware settings
    ./System/App/App-settigs.nix
    ./System/Security.nix
    ./System/PkgMan.nix
    ./System/Locale.nix
    ./System/EnVars.nix
    ./System/Users.nix
    ./System/Boot.nix
  ];

  #Enable experimental features
  nix.settings = {
    experimental-features = [
      "nix-command"
      "flakes"
    ];
    warn-dirty = false; # Disable warning about dirty git repos
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.11"; # Did you read the comment? <yes, i did>
}
